# Generated by Django 2.2.1 on 2019-06-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='auteur',
        ),
        migrations.AddField(
            model_name='manga',
            name='auteur',
            field=models.ManyToManyField(related_name='mangas', to='manga.Auteur'),
        ),
    ]
