# Generated by Django 2.2.1 on 2019-06-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_auto_20190607_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='titre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
