# Generated by Django 2.2.1 on 2019-06-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_auto_20190607_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='manga',
            field=models.ManyToManyField(related_name='auteurs', to='manga.Manga'),
        ),
    ]
