# Generated by Django 2.2.1 on 2019-06-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_auteur_manga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='manga',
            field=models.ManyToManyField(null=True, related_name='auteurs', to='manga.Manga'),
        ),
    ]
