# Generated by Django 2.2.1 on 2019-06-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_auto_20190607_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='manga',
            field=models.ManyToManyField(blank=True, related_name='auteurs', to='manga.Manga'),
        ),
    ]
