# Generated by Django 2.2.1 on 2019-06-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0007_auto_20190607_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auteur',
            name='manga',
        ),
    ]
